### ISSUE TITLE
Qt5PrintSupport.dll missing

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textilosaurus#4]
**Issue**
Launching **textilosaurus.exe** triggers an error message:
![textilosaurus-2017 12 06 - 2017-12-06 - error - 001](https://user-images.githubusercontent.com/9025757/33679974-dc49854a-dac8-11e7-817f-ec491fa88fb1.png)

There is another error message if **Qt5PrintSupport.dll** is not the right version:
![textilosaurus-2017 12 06 - 2017-12-06 - error - 002](https://user-images.githubusercontent.com/9025757/33680031-0cb47438-dac9-11e7-869b-5967c7358ca6.png)

**System**
_Windows 8 x64_

**Textilosaurus version**
 _2017.12.06-0e93b8d_

**Comment by martinrotter** [comment]
Yes, fixed. Please try latest develompment version. - https://transfer.sh/aDsM6/textilosaurus-2017.12.06-f0e9d40-win64.7z

**Comment by martinrotter** [comment]
And let me know if it works.

**Comment by smaragdus** [comment]
No error message (missing DLL) at launching **Textilosaurus** version **2017.12.06-f0e9d40**, thanks.

**Comment by smaragdus** [comment]
**Off-topic**
Please re-consider the versioning scheme.

**Comment by martinrotter** [comment]
"Please re-consider the versioning scheme." Why?

**Comment by smaragdus** [comment]
Date versioning scheme hints nothing about programs' development and maturity. I like [RSS Guard](https://github.com/martinrotter/rssguard) [versioning](https://github.com/martinrotter/rssguard/releases) better.

**Comment by martinrotter** [comment]
I understand the semantic versioning has its undoubtable advantages, I will think about this, because for Textilosaurus, I plan to use a bit different development strategy.

In RSS Guard, there are *major* releases which introduce new bigger features, and *minor* releases which fix bugs only.

In Textilosaurus, I do not plan to distinguish between *major* releases and *minor* releases, I just plan to add new features and bug fixes rapidly, not in independent release. Thus, I feel that semantic versioning would not fit this strategy well. But I will think about this for tady and decide on the evening. Thank you for hinting this out.

**Comment by martinrotter** [comment]
Btw, what do you overally think about Textilosaurus so far? Yes, it is pre-alpha quality, but what is your opinion?

**Comment by martinrotter** [comment]
Yes, I will have to find a way how to make that menu bit shorter, it cannot be "split to two columns", no such API is available or at least I do not know how to do it. Let me try some stuff.
